# --------------------------------------------------
# Site Settings
# --------------------------------------------------
  
# Menu
menu:
  home: / || 首页
  galleries: /galleries || 摄影
  archives: /archives || 归档
  tags: /tags || 标签
  categories: /categories || 分类
  about: /about || 关于

# Color
color:
  text: "#33333D"
  text-secondary: "#4e4e4e"
  text-third: "#999999"
  background: "#FFFFFF"
  background-secondary: "#f6f8fa"
  text-dark: "#dddddd"
  text-secondary-dark: "#9899ab"
  text-third-dark: "#7d8594"
  background-dark: "#1e2128"
  background-secondary-dark: "#1a1d22"
  link: "#FF3B00"

# Favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Font
font:
  size: 14px
  family:

# Background Image
background_image:

# Loading
loading: /images/theme/loading.gif

# Preview
preview:
  enable: true
  model: wave  # cloud
  welcome_image: /images/theme/2005706.jpg
  motto:
    default: 努力提升自己，如此不负青春年华。
    color: '#FFFFCC'
    api:  # http://localhost:3000/api/motto

# Copyright
copyright: <p>Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=1137102347 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/izhaoo || icongithub-fill || '#24292E'
  email: mailto:izhaoo@163.com || iconmail

# Fab (Float Action Button)
fab:
  enable: true
  always_show: false

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Post Image
post_image:
  random: local # galleries
  default: /images/theme/2005706.jpg

# Page Size
post_page_size:
  width: 1000px

# Donate
donate:
  enable: true
  alipay: https://pic.izhaoo.com/alipay.jpg
  wechat: https://pic.izhaoo.com/wechat.jpg

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # markdown text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 摄影
  subtitle: Photography

# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: true
  type: valine
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Caption
caption:
  enable: true

# Valine
valine:
  appId:
  appKey:
  placeholder: 雁过留痕
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  appKey:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Daovoice
daovoice:
  enable: true
  appId: abcdefg  # app_id

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading: /images/theme/loading.gif

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Xcode
    dark: Solarized Dark

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: //at.alicdn.com/t/font_1445822_onl0g0h21np.css

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: # id
  google: # id
  tencent: # id
  cnzz: # id

# Custom
custom:
  head:
  foot:
  css:
  js:

# TOC 配置项 toc 用于设置 文章目录，开启后会在文章内容右侧生成目录，点击目录可平滑到对应的标题处
# 全局开启 文章目录 后，可以在文章 Front-matter 中添加 toc 字段单独控制该文章是否展示文章目录。
# toc: false # 关闭文章目录
toc:
  enable: true
  min_depth: 1
  max_depth: 3